### PR TITLE
Initialize the truffle project

### LINKED ISSUE #16: Initialize Truffle Project
**Is your feature request related to a problem? Please describe.**

There is no truffle project currently!

**Describe the solution you'd like**

A truffle project should be initialized.

**Describe alternatives you've considered**

Alternatives to truffle (javascript) include, hardhat (typescript) and brownie (python)

### PR DESCRIPTION
**Pull request by skellet0r**
Initialized the truffle project by running `truffle init`

Resolves EthBuilders/EthGlobal-West-Texas-Oil#16

### CODE REVIEW

**Comment by skellet0r** [comment]
@ermz, @andykeh710 does this look good to merge in?
Need approvals before it gets merged in :cry:

**Review by ermz — DISMISSED** [review]
Look good!!

**Comment by skellet0r** [comment]
@ermz sorry I updated the history on my fork, and accidentally cancelled out your review :frowning:

**Review by ermz — APPROVED** [review]

**Review by KenMan79 — APPROVED** [review]
Looks great

**Pull request merged**
