### PR TITLE
React-App Initalized

### PR DESCRIPTION
**Pull request by KenMan79**
used npm init -y
ran yarn install
ran yarn create react-app my-ethglobal-west-texas-oil-main

### CODE REVIEW

**Comment by skellet0r** [comment]
@andykeh710 @ermz how's this look by the way?

**Review by skellet0r — CHANGES_REQUESTED** [review]
Minor detail but should we change the name of the react app project to something shorter?
Maybe just `west-texas-oil` or `frontend` or `wto-front`. It's an aesthetics thing I guess nbd.
Good job initializing though. Just needs two approvals and it can be merged in.

**Comment by ermz** [comment]
Agree with Edward the name should be shorter. It'll be easier to find/navigate into

**Review by andykeh710 — APPROVED** [review]
Looking good!

**Pull request closed without merging**
